version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: questionnaire_php
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    restart: unless-stopped
